kind: pipeline
type: docker
name: build-release-images
trigger:
  event:
    exclude:
    - pull_request
  ref:
    - refs/tags/**

platform:
  os: linux
  arch: amd64

steps:
  # Set tags for main branch - release tag and 'latest'
- name: make-tags-main
  image: node
  commands:
    - echo -n "${DRONE_TAG}, latest" > .tags

  # Build containers from main branch when released
- name: build-main
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    provenance: false
    registry: git.mrmeeb.stream
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: git.mrmeeb.stream/mrmeeb/cronicle
    platforms:
      - linux/arm64
      - linux/amd64

- name: release
  image: goreleaser/goreleaser
  environment:
    GITEA_TOKEN:
      from_secret: gitea_token
  commands:
    - goreleaser release

- name: notify
  image: plugins/slack
  when:
    status:
    - success
    - failure
  settings:
    webhook: 
      from_secret: slack_webhook

---
kind: pipeline
type: docker
name: build-develop-images
trigger:
  event:
    exclude:
    - pull_request
  branch:
    - develop

platform:
  os: linux
  arch: amd64

steps:
  # Set tags for develop branch - git commit SHA and 'develop'
- name: make-tags-develop
  image: node
  commands:
    - echo -n "${DRONE_COMMIT_SHA:0:8}, develop" > .tags
   
  # Build containers from develop branch
- name: build-develop
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    provenance: false
    registry: git.mrmeeb.stream
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: git.mrmeeb.stream/mrmeeb/cronicle
    platforms:
      - linux/arm64
      - linux/amd64

- name: notify
  image: plugins/slack
  when:
    status:
    - success
    - failure
  settings:
    webhook: 
      from_secret: slack_webhook