dist: dist-gitea

build:
  skip: true

archives:
- format: binary

release:
  draft: true
  gitea:
    owner: MrMeeb
    name: cronicle-docker

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# .goreleaser.yaml
gitea_urls:
  api: https://git.mrmeeb.stream/api/v1
  download: https://git.mrmeeb.stream
  # set to true if you use a self-signed certificate
  skip_tls_verify: false